###

GET http://localhost:3000/user/ 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1fcmljaGFyZCIsImlhdCI6MTY5MTc1NzQ4OX0.ivlpkhh5IQYvsANsnzu-dzXGl0r65o5IFFygoPugF90
###
POST http://localhost:3000/register/
    Content-Type: application/json

    {
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}
###

POST http://localhost:3000/login/
    Content-Type: application/json

    {
  "username":"adam_richard",
  "password":"richard_567"
}

###

